const char	*error_msg[] =
{
	"Success",
	"No such nick or channel name",
	"No such server",
	"No such channel",
	"Cannot send to channel",
	"Too many channels",
	"No such nick",
	"Too many targets",
	"No origin",
	"No recipient",
	"No text to send",
	"No toplevel",
	"Wildtoplevel",
	"Unknown command",
	"No MOTD",
	"No administrative info",
	"File error",
	"No nickname given",
	"Erroneus nickname",
	"Nickname in use",
	"Nick collision",
	"User not in channel",
	"Not on channel",
	"User on channel",
	"Not logged in",
	"Summon disabled",
	"Users disabled",
	"Not registered",
	"Need more params",
	"Already registered",
	"Permission denied",
	"Password mismatch",
	"You are banned from this server",
	"Key already set",
	"Channel is full",
	"Unknown mode",
	"Invite only channel",
	"Banned from channel",
	"Bad channel key",
	"No privileges",
	"Channel operator privileges needed",
	0
};
